spring.application.name=APIBiblioteca

# PostgreSQL Configuration
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/bdbiblioteca
spring.datasource.username=postgres
spring.datasource.password=1234

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.display-operation-id=true
