-- =====================================================================
-- Sistema Integral de Gestion Bibliotecaria (UNTELS) - script.sql
-- Script de creacion de base de datos PostgreSQL + datos de prueba.
--
-- Los nombres de tabla/columna son EXACTAMENTE los que genera Hibernate
-- en tiempo de ejecucion (spring.jpa.hibernate.ddl-auto=update), ya que
-- Spring Boot aplica snake_case a los nombres logicos declarados en
-- @Column/@JoinColumn (ej. "stockTotal" -> stock_total, "idEstudiante"
-- -> id_estudiante). Este script fue verificado contra el esquema real
-- generado por la aplicacion.
--
-- Uso: psql -U postgres -d bdbiblioteca -f script.sql
-- (crear antes la base de datos vacia: CREATE DATABASE bdbiblioteca;)
-- =====================================================================

DROP TABLE IF EXISTS notificaciones CASCADE;
DROP TABLE IF EXISTS sanciones CASCADE;
DROP TABLE IF EXISTS prestamos CASCADE;
DROP TABLE IF EXISTS libros CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS configuracion_biblioteca CASCADE;

-- =====================================================================
-- Tabla: usuarios (Administrador / Bibliotecario / Estudiante)
-- =====================================================================
CREATE TABLE usuarios (
    id_usuario  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(30)  NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    codigo      VARCHAR(20)  NOT NULL UNIQUE,
    carnet      VARCHAR(20),
    dni         VARCHAR(8),
    nombre      VARCHAR(100) NOT NULL,
    email       VARCHAR(100) NOT NULL,
    telefono    VARCHAR(20),
    rol         VARCHAR(20)  NOT NULL CHECK (rol IN ('ADMIN', 'BIBLIOTECARIO', 'ESTUDIANTE')),
    carrera     VARCHAR(80),
    ciclo       INTEGER,
    estado      VARCHAR(20)  NOT NULL CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE INDEX idx_usuarios_rol ON usuarios (rol);
CREATE INDEX idx_usuarios_estado ON usuarios (estado);
CREATE INDEX idx_usuarios_dni ON usuarios (dni);

-- =====================================================================
-- Tabla: libros (catalogo bibliografico, 100% local)
-- =====================================================================
CREATE TABLE libros (
    id_libro     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo       VARCHAR(100) NOT NULL,
    autor        VARCHAR(100) NOT NULL,
    isbn         VARCHAR(20)  NOT NULL UNIQUE,
    editorial    VARCHAR(100),
    anio         INTEGER,
    categoria    VARCHAR(30)  NOT NULL,
    stock        INTEGER      NOT NULL CHECK (stock >= 0),
    stock_total  INTEGER      NOT NULL CHECK (stock_total >= 0),
    descripcion  VARCHAR(500),
    recurso      VARCHAR(300),
    CHECK (stock <= stock_total)
);

CREATE INDEX idx_libros_categoria ON libros (categoria);
CREATE INDEX idx_libros_titulo ON libros (titulo);
CREATE INDEX idx_libros_autor ON libros (autor);

-- =====================================================================
-- Tabla: prestamos (circulacion: solicitar / aprobar / rechazar / devolver)
-- =====================================================================
CREATE TABLE prestamos (
    id_prestamo        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_libro           INTEGER NOT NULL REFERENCES libros (id_libro),
    id_estudiante      INTEGER NOT NULL REFERENCES usuarios (id_usuario),
    fecha              TIMESTAMP NOT NULL,
    fecha_recojo       TIMESTAMP,
    fecha_entrega      TIMESTAMP NOT NULL,
    fecha_confirmacion TIMESTAMP,
    fecha_devolucion   TIMESTAMP,
    estado             VARCHAR(20) NOT NULL CHECK (estado IN ('solicitado', 'vigente', 'rechazado', 'devuelto', 'vencido')),
    motivo             VARCHAR(255),
    curso              VARCHAR(100),
    observaciones      VARCHAR(500),
    estado_devolucion  VARCHAR(30),
    observaciones_dev  VARCHAR(500)
);

CREATE INDEX idx_prestamos_estado ON prestamos (estado);
CREATE INDEX idx_prestamos_estudiante ON prestamos (id_estudiante);
CREATE INDEX idx_prestamos_libro ON prestamos (id_libro);

-- =====================================================================
-- Tabla: sanciones
-- =====================================================================
CREATE TABLE sanciones (
    id_sancion      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estudiante   INTEGER NOT NULL REFERENCES usuarios (id_usuario),
    motivo          VARCHAR(200),
    dias_suspension INTEGER NOT NULL CHECK (dias_suspension >= 0),
    multa           DOUBLE PRECISION NOT NULL CHECK (multa >= 0),
    estado          VARCHAR(20) NOT NULL CHECK (estado IN ('activa', 'cumplida')),
    fecha_creacion  TIMESTAMP NOT NULL,
    fecha_fin       TIMESTAMP
);

CREATE INDEX idx_sanciones_estado ON sanciones (estado);
CREATE INDEX idx_sanciones_estudiante ON sanciones (id_estudiante);

-- =====================================================================
-- Tabla: notificaciones
-- =====================================================================
CREATE TABLE notificaciones (
    id_notificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estudiante   INTEGER NOT NULL REFERENCES usuarios (id_usuario),
    tipo            VARCHAR(30)  NOT NULL,
    mensaje         VARCHAR(500) NOT NULL,
    fecha           TIMESTAMP    NOT NULL,
    leida           BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_notificaciones_estudiante ON notificaciones (id_estudiante);
CREATE INDEX idx_notificaciones_leida ON notificaciones (leida);

-- =====================================================================
-- Tabla: configuracion_biblioteca (fila unica de parametros globales)
-- =====================================================================
CREATE TABLE configuracion_biblioteca (
    id_configuracion_biblioteca INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dias_max_prestamo INTEGER NOT NULL CHECK (dias_max_prestamo > 0),
    limite_prestamos  INTEGER NOT NULL CHECK (limite_prestamos > 0),
    multa_por_dia     DOUBLE PRECISION NOT NULL CHECK (multa_por_dia >= 0),
    scheduler_activo  BOOLEAN NOT NULL DEFAULT TRUE,
    notif_email       BOOLEAN NOT NULL DEFAULT FALSE,
    alerta_stock      BOOLEAN NOT NULL DEFAULT TRUE,
    modo_mant         BOOLEAN NOT NULL DEFAULT FALSE
);

-- =====================================================================
-- DATOS DE PRUEBA
-- Contraseña para TODAS las cuentas de prueba: "Password123!"
-- (hash BCrypt real, generado con BCryptPasswordEncoder del propio proyecto)
-- =====================================================================

-- usuarios: id_usuario 1..8 en este orden de insercion
INSERT INTO usuarios (username, password, codigo, carnet, dni, nombre, email, telefono, rol, carrera, ciclo, estado) VALUES
('admin1',       '$2a$10$nGtL6bsIFCiMatPZX4j51.4dL3CialcvxAS3GFTjPidu9rHjiuPgW', 'ADM-0001', NULL,        '10000001', 'Admin General',      'admin1@untels.edu.pe',       '999000001', 'ADMIN',         NULL,                  NULL, 'ACTIVO'),   -- 1
('biblio1',      '$2a$10$nGtL6bsIFCiMatPZX4j51.4dL3CialcvxAS3GFTjPidu9rHjiuPgW', 'BIB-0001', NULL,        '10000002', 'Rosa Mendoza',        'rmendoza@untels.edu.pe',     '999000002', 'BIBLIOTECARIO', NULL,                  NULL, 'ACTIVO'),   -- 2
('biblio2',      '$2a$10$nGtL6bsIFCiMatPZX4j51.4dL3CialcvxAS3GFTjPidu9rHjiuPgW', 'BIB-0002', NULL,        '10000003', 'Jorge Salinas',       'jsalinas@untels.edu.pe',     '999000003', 'BIBLIOTECARIO', NULL,                  NULL, 'ACTIVO'),   -- 3
('jperez',       '$2a$10$nGtL6bsIFCiMatPZX4j51.4dL3CialcvxAS3GFTjPidu9rHjiuPgW', 'EST-1001', 'C-1001',    '20000001', 'Juan Perez',          'jperez@untels.edu.pe',       '988000001', 'ESTUDIANTE',    'Ingenieria de Sistemas', 5, 'ACTIVO'),  -- 4
('mlopez',       '$2a$10$nGtL6bsIFCiMatPZX4j51.4dL3CialcvxAS3GFTjPidu9rHjiuPgW', 'EST-1002', 'C-1002',    '20000002', 'Maria Lopez',         'mlopez@untels.edu.pe',       '988000002', 'ESTUDIANTE',    'Ingenieria Industrial',  3, 'ACTIVO'),  -- 5
('cramirez',     '$2a$10$nGtL6bsIFCiMatPZX4j51.4dL3CialcvxAS3GFTjPidu9rHjiuPgW', 'EST-1003', 'C-1003',    '20000003', 'Carlos Ramirez',      'cramirez@untels.edu.pe',     '988000003', 'ESTUDIANTE',    'Administracion',         7, 'ACTIVO'),  -- 6
('atorres',      '$2a$10$nGtL6bsIFCiMatPZX4j51.4dL3CialcvxAS3GFTjPidu9rHjiuPgW', 'EST-1004', 'C-1004',    '20000004', 'Ana Torres',          'atorres@untels.edu.pe',      '988000004', 'ESTUDIANTE',    'Contabilidad',           2, 'INACTIVO'),-- 7
('lfernandez',   '$2a$10$nGtL6bsIFCiMatPZX4j51.4dL3CialcvxAS3GFTjPidu9rHjiuPgW', 'EST-1005', 'C-1005',    '20000005', 'Luis Fernandez',      'lfernandez@untels.edu.pe',   '988000005', 'ESTUDIANTE',    'Ingenieria de Sistemas', 9, 'ACTIVO');  -- 8

-- libros: id_libro 1..5 en este orden de insercion
INSERT INTO libros (titulo, autor, isbn, editorial, anio, categoria, stock, stock_total, descripcion, recurso) VALUES
('Redes de Computadoras',              'Andrew Tanenbaum',  '9786073209000', 'Pearson',      2019, 'TECNICO',   5, 5, 'Fundamentos de redes de computadoras.',              NULL), -- 1
('Bases de Datos Avanzadas',           'Raghu Ramakrishnan','9789701068783', 'McGraw-Hill',  2018, 'TECNICO',   1, 3, 'Modelado y administracion de bases de datos.',       NULL), -- 2
('Contabilidad General',               'Zeida Garcia',      '9789972615400', 'San Marcos',   2020, 'REFERENCIA',2, 4, 'Principios basicos de contabilidad.',                 NULL), -- 3
('Cien Anios de Soledad',              'Gabriel Garcia Marquez', '9788439732471', 'Sudamericana', 1967, 'FICCION', 4, 4, 'Novela emblematica del realismo magico.',          NULL), -- 4
('Introduccion a la Administracion',   'Idalberto Chiavenato','9786071511477', 'McGraw-Hill', 2017, 'REFERENCIA', 0, 2, 'Conceptos fundamentales de administracion.',       NULL); -- 5

-- prestamos: referencian id_libro / id_estudiante ya conocidos
INSERT INTO prestamos (id_libro, id_estudiante, fecha, fecha_recojo, fecha_entrega, fecha_confirmacion, fecha_devolucion, estado, motivo, curso, observaciones, estado_devolucion, observaciones_dev) VALUES
(1, 4, NOW() - INTERVAL '30 days', NOW() - INTERVAL '29 days', NOW() - INTERVAL '16 days', NULL, NOW() - INTERVAL '17 days', 'devuelto',   'Trabajo de investigacion de redes', 'Redes I',        'Ninguna', 'BUENO', 'Libro devuelto en buen estado'),
(2, 5, NOW() - INTERVAL '10 days', NOW() - INTERVAL '9 days',  NOW() + INTERVAL '5 days',  NULL, NULL,                       'vigente',    'Proyecto de curso de BD',           'Base de Datos',  'Ninguna', NULL,    NULL),
(3, 6, NOW() - INTERVAL '20 days', NOW() - INTERVAL '19 days', NOW() - INTERVAL '5 days',  NULL, NULL,                       'vencido',    'Consulta de contabilidad',          'Contabilidad II','Ninguna', NULL,    NULL),
(4, 8, NOW() - INTERVAL '1 days',  NULL,                       NOW() + INTERVAL '14 days', NULL, NULL,                       'solicitado', 'Lectura recomendada del curso',     'Literatura',     'Ninguna', NULL,    NULL),
(5, 4, NOW() - INTERVAL '3 days',  NULL,                       NOW() + INTERVAL '11 days', NULL, NULL,                       'rechazado',  'Consulta rapida',                   'Gestion',        'Ninguna', NULL,    NULL);

-- sanciones
INSERT INTO sanciones (id_estudiante, motivo, dias_suspension, multa, estado, fecha_creacion, fecha_fin) VALUES
(6, 'Devolucion tardia de libro: Contabilidad General (5 dias de retraso)', 5, 5.00, 'activa',   NOW() - INTERVAL '5 days',  NOW() + INTERVAL '2 days'),
(5, 'Devolucion tardia de libro: Redes de Computadoras (2 dias de retraso)', 2, 2.00, 'cumplida', NOW() - INTERVAL '60 days', NOW() - INTERVAL '58 days');

-- notificaciones
INSERT INTO notificaciones (id_estudiante, tipo, mensaje, fecha, leida) VALUES
(4, 'confirmacion', 'Tu prestamo del libro ''Redes de Computadoras'' ha sido aprobado', NOW() - INTERVAL '29 days', TRUE),
(5, 'confirmacion', 'Tu prestamo del libro ''Bases de Datos Avanzadas'' ha sido aprobado', NOW() - INTERVAL '9 days', FALSE),
(6, 'sancion',      'Se ha generado una sancion por devolucion tardia. Dias de suspension: 5, Multa: S/5.00', NOW() - INTERVAL '5 days', FALSE),
(4, 'rechazo',      'Tu solicitud de prestamo del libro ''Introduccion a la Administracion'' ha sido rechazada: No hay ejemplares disponibles', NOW() - INTERVAL '3 days', FALSE);

-- configuracion_biblioteca (fila unica)
INSERT INTO configuracion_biblioteca (dias_max_prestamo, limite_prestamos, multa_por_dia, scheduler_activo, notif_email, alerta_stock, modo_mant) VALUES
(15, 3, 2.00, TRUE, FALSE, TRUE, FALSE);
